package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'ConfigWithBranches'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("ConfigWithBranches")) {
    features {
        add {
            feature {
                type = "keepRules"
                param("limit.type", "lastNBuilds")
                param("keepData.2.type", "logs")
                param("keepData.4.type", "statistics")
                param("keepData.1.type", "artifacts")
                param("ruleDisabled", "false")
                param("keepData.3.type", "history")
                param("keepData.1.artifactsPatterns", "+:**/*overandover")
                param("limit.buildsCount", "5")
                param("preserveArtifacts", "true")
            }
        }
    }
}
