package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.projectFeatures.ProjectReportTab
import jetbrains.buildServer.configs.kotlin.v2019_2.projectFeatures.projectReportTab
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        remove {
            projectReportTab {
                id = "PROJECT_EXT_70"
                title = "test"
                startPage = "test.html"
                buildType = "ReportTabPerBranch_ConfigWithBranches"
                sourceBuildRule = ProjectReportTab.SourceBuildRule.LAST_FINISHED
                param("revisionRuleBranchFilter", "+:*")
            }
        }
        add {
            projectReportTab {
                id = "PROJECT_EXT_61"
                title = "test"
                startPage = "test.html"
                buildType = "ReportTabPerBranch_Test"
                sourceBuildRule = ProjectReportTab.SourceBuildRule.LAST_FINISHED
                param("revisionRuleBranchFilter", "+:<default>")
            }
        }
    }
}
