package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'HttpsGithubComInnayanMyrepositoryRefsHeadsMaster'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, GitVcsRoot({
    id("HttpsGithubComInnayanMyrepositoryRefsHeadsMaster")
    name = "https://github.com/innayan/myrepository#refs/heads/master"
    url = "https://github.com/innayan/myrepository"
    branch = "refs/heads/asasas"
    branchSpec = "+:*"
    authMethod = password {
        userName = "innayan"
        password = "credentialsJSON:8b81c90d-e4be-4b96-bd84-fdf57a093314"
    }
}))

